### ISSUE TITLE
ssh到jumpserver,不显示任何资产,web terminal 时常连接失败

### ISSUE THREAD

**Issue by tri7stan** [jumpserver/coco#101]
```
  XX, 欢迎使用Jumpserver开源跳板机系统  

    1) 输入 ID 直接登录 或 输入部分 IP,主机名,备注 进行搜索登录(如果唯一).
    2) 输入 / + IP, 主机名 or 备注 搜索. 如: /ip
    3) 输入 p 显示您有权限的主机.
    4) 输入 g 显示您有权限的节点
    5) 输入 g + 组ID 显示节点下主机. 如: g1
    6) 输入 h 帮助.
    0) 输入 q 退出.

Opt> p

ID   Hostname IP               LoginAs Comment                                                                                                     

总共: 0 匹配: 0

Opt> 
```

**Comment by wojiushixiaobai** [comment]
@tri7stan 资产授权给登陆用户没，确定coco已经在jumpserver上注册

**Comment by tri7stan** [comment]
都有 luna界面能看到资产 但是连接经常失败发自我的华为手机-------- 原始邮件 --------主题：Re: [jumpserver/coco] ssh到jumpserver,不显示任何资产,web terminal 时常连接失败 (#101)发件人：wojiushixiaobai 收件人：jumpserver/coco 抄送：tri7stan ,Mention @tri7stan 资产授权给登陆用户没，确定coco已经在jumpserver上注册

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jumpserver/coco","title":"jumpserver/coco","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jumpserver/coco"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wojiushixiaobai in #101: @tri7stan 资产授权给登陆用户没，确定coco已经在jumpserver上注册"}],"action":{"name":"View Issue","url":"https://github.com/jumpserver/coco/issues/101#issuecomment-422762759"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jumpserver/coco/issues/101#issuecomment-422762759",
"url": "https://github.com/jumpserver/coco/issues/101#issuecomment-422762759",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jumpserver/coco] ssh到jumpserver,不显示任何资产,web terminal 时常连接失败 (#101)",
"sections": [
{
"text": "",
"activityTitle": "**wojiushixiaobai**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@wojiushixiaobai",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jumpserver/coco\",\n\"issueId\": 101,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jumpserver/coco\",\n\"issueId\": 101\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jumpserver/coco/issues/101#issuecomment-422762759"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 379740541\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by wojiushixiaobai** [comment]
@tri7stan 懂了，参考最新的安装文档，把nginx部分对着修改下，一定要注意，jumpserver/coco/luna的版本要一致。
经常连接失败是socket的问题，nginx代理需要设置一下长连接

**Comment by tri7stan** [comment]
然而ssh没资产原因是啥 现在coco和jumpserver都是git pull到最新 luna是1.4.1发自我的华为手机-------- 原始邮件 --------主题：Re: [jumpserver/coco] ssh到jumpserver,不显示任何资产,web terminal 时常连接失败 (#101)发件人：wojiushixiaobai 收件人：jumpserver/coco 抄送：tri7stan ,Mention @tri7stan 懂了，参考最新的安装文档，把nginx部分对着修改下，一定要注意，jumpserver/coco/luna的版本要一致。
经常连接失败是socket的问题，nginx代理需要设置一下长连接

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jumpserver/coco","title":"jumpserver/coco","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jumpserver/coco"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wojiushixiaobai in #101: @tri7stan 懂了，参考最新的安装文档，把nginx部分对着修改下，一定要注意，jumpserver/coco/luna的版本要一致。\r\n经常连接失败是socket的问题，nginx代理需要设置一下长连接"}],"action":{"name":"View Issue","url":"https://github.com/jumpserver/coco/issues/101#issuecomment-422770422"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jumpserver/coco/issues/101#issuecomment-422770422",
"url": "https://github.com/jumpserver/coco/issues/101#issuecomment-422770422",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jumpserver/coco] ssh到jumpserver,不显示任何资产,web terminal 时常连接失败 (#101)",
"sections": [
{
"text": "",
"activityTitle": "**wojiushixiaobai**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@wojiushixiaobai",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jumpserver/coco\",\n\"issueId\": 101,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jumpserver/coco\",\n\"issueId\": 101\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jumpserver/coco/issues/101#issuecomment-422770422"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 379740541\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by wo1fb0ss** [comment]
> @tri7stan 懂了，参考最新的安装文档，把nginx部分对着修改下，一定要注意，jumpserver/coco/luna的版本要一致。
> 经常连接失败是socket的问题，nginx代理需要设置一下长连接

我也是同样的问题，版本都用的是最新版，nginx也按照最新的文档配置了，问题还是没有解决
