### ISSUE TITLE
命令记录缺失及分割错误

### ISSUE THREAD

**Issue by vki** [jumpserver/coco#11]
<img width="425" alt="2017-08-08 11 14 32" src="https://user-images.githubusercontent.com/538786/29106828-c4da193c-7d09-11e7-83ee-15460d1f7c2f.png">

数据库记录信息也是错误的，看了源码应该是proxy.py client_channel recv 后数据解析分割的问题

**Comment by dominicx** [comment]
同样，问题很大。搞得半途而废。

**Comment by liuzheng** [comment]
please try again
