### ISSUE TITLE
coco用户通过xshell登录后，会异步查询用户的机器和节点信息。如果xshell不退出，新机器、节点就显示不了。

### ISSUE THREAD

**Issue by xionghui** [jumpserver/coco#140]
coco用户通过xshell登录后，会异步查询用户的机器和节点信息。如果xshell不退出，新机器、节点就显示不了。

**Comment by ibuler** [comment]
原来版本是实时查的，当资产很多时，每次p或者查询都会api调用，速度非常慢

**Comment by xionghui** [comment]
我现在增加用户可以手动refresh的功能，仍然是异步，用户下次再p的时候，至少是最新的机器信息。这个pr我回头合入一下？贡献点力量。

**Comment by xionghui** [comment]
否则用户只能是退出登录，然后再登陆才能同步一次。
