### ISSUE TITLE
如何通过python代码连接coco进行交互，并通过coco连接到内部资产？

### ISSUE THREAD

**Issue by Amos-x** [jumpserver/coco#239]
coco连接，目前可以web端，可以ssh终端，但是如果想写一些python脚本，需要联机到内网资源，可以通过代码连接到coco，然后再指定连接到具体的内网资源吗。

**Comment by jasper-zhang** [comment]
可以，用代码实现ssh client即可，`paramiko`有现成的库

**Comment by Amos-x** [comment]
thanks，我已经实现了，谢谢

**Comment by daimon99** [comment]
这个什么思路做呢？可否给个例子呀？ @Amos-x @jasper-zhang

**Comment by Amos-x** [comment]
你看一下coco的源码，coco的源码里有实现ssh server。我们并没有用ssh client，通过pty来访问。因为我只是想要ssh代理转发，所以只是查看coco的源码中实现代理转发的那块。
