### ISSUE TITLE
coco登录错误：Permission denied (publickey).

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/coco#25]
coco注册之后，使用命令：ssh -p 2222 USERNAME@IP登录时总是报错：
`(py3) ➜  coco git:(master) ✗ ssh -p 2222 seven@172.16.33.223`
`Permission denied (publickey).`
`(py3) ➜  coco git:(master) ✗ cat /etc/centos-release`
`CentOS Linux release 7.4.1708 (Core) `
`(py3) ➜  coco git:(master) ✗ `
`(py3) ➜  coco git:(master) ✗ ls keys/ -al`
`total 8`
`drwxr-xr-x. 2 seven wheel   61 11月 21 11:24 .`
`drwxr-xr-x. 8 seven wheel  242 11月 21 11:23 ..`
`-rw-r--r--. 1 seven wheel   73 11月 21 11:24 .access_key`
`-rw-r--r--. 1 seven wheel    0 9月   5 13:32 .gitkeep`
`-rw-r--r--. 1 seven wheel 1679 11月 21 11:18 host_rsa_key`
`(py3) ➜  coco git:(master)`
另外请教：
keys/host_rsa_key这个私钥是干什么用的？我试了一下，它并不是自动生成的，而且它不在.gitignore中。

**Comment by liuzheng** [comment]
old issue
