### ISSUE TITLE
coco 登录用户退出后，目标服务器上出现大量的notty进程

### ISSUE THREAD

**Issue by w55554** [jumpserver/coco#33]
在coco上用DevUser 用户去登录 目标服务器A ，正常操作完成退出后，A 服务器上会出现大量的 DevUser@notty 进程,这个怎么解决一下呢。

**Comment by w55554** [comment]
原因可能是我的jumpserver的用户已经退出终端了，但是 coco 和目标服务器的连接没有中断导致的。

**Comment by ibuler** [comment]
不是，是ansible推送后保持的长连接

**Comment by w55554** [comment]
下图是我反应的问题，如何让这些长连接超时断开呢？
![长连接](http://ow7h4ercl.bkt.clouddn.com/1.png)
