### ISSUE TITLE
安装jumpserver1.3.3和coco1.3.3 ，jms库如何升级

### ISSUE THREAD

**Issue by xionghui** [jumpserver/coco#73]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/proxy.py", line 54, in proxy
    if system_user.login_mode == MANUAL_LOGIN and not system_user.username:
AttributeError: 'SystemUser' object has no attribute 'login_mode'

**jms**/models.py

class SystemUser(Decoder):
    id = 0
    name = ""
    username = ""
    protocol = "ssh"
    auth_method = "P"
    comment = ""
    password = ""
    priority = 0
    private_key = None

    def __str__(self):
        return self.username

    def __repr__(self):
        return self.username

**Comment by jokimina** [comment]
pip  install -r  coco/requirements/requirements.txt
或者单独更新
pip install jumpserver-python-sdk==0.0.44

**Comment by xionghui** [comment]
非常感谢，我更新一下试一下。

**Comment by xionghui** [comment]
再请教一个问题啊，最新版本应该是支持asset的domain网关了吧。但是jumpserver的asset接口返回没有domain相关信息：

(py3) [root@120923cde472 coco]# curl -X GET -H "Content-Type:application/json" -H "Authorization: Sign  2e514eda-2497-4935-a972-34b4d3b85447:ZTY5ZTk3MWExYzU2ODk5ZjI1YzJiMTgyMTc5YzA4MjY=" -H "Date:Fri, 20 Jul 2018 12:59:05 GMT" http://127.0.0.1:8080/api/assets/v1/system-user/fa09628b-d2c5-4a48-96e6-c2cc9f55100e/ | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   555  100   555    0     0  15331      0 --:--:-- --:--:-- --:--:-- 15857
{
    "id": "fa09628b-d2c5-4a48-96e6-c2cc9f55100e",
    "unreachable_amount": 0,
    "reachable_amount": 0,
    "unreachable_assets": [],
    "reachable_assets": [],
    "assets_amount": 1,
    "name": "root",
    "username": "root",
    "comment": "",
    "date_created": "2018-07-20 11:10:36 +0000",
    "date_updated": "2018-07-20 11:25:58 +0000",
    "created_by": null,
    "priority": 10,
    "protocol": "ssh",
    "auto_push": false,
    "sudo": "/bin/whoami",
    "shell": "/bin/bash",
    "login_mode": "manual",
    "nodes": [
        "22cd7bdc-2d24-4992-bd57-475bceee9dc5"
    ],
    "assets": [
        "10a8d080-c71c-45e6-bfaf-bca332071caf"
    ],
    "get_login_mode_display": "Manually login"
}
而coco是需要根据asset的字段进行处理的：
![default](https://user-images.githubusercontent.com/2037425/43053685-97e39b74-8e60-11e8-8512-3112537b2b69.png)

这就有问题啊！

**Comment by xionghui** [comment]
好像可以了 非常感谢！
