### ISSUE TITLE
字段名称不一致问题

### ISSUE THREAD

**Issue by hellorocky** [jumpserver/coco#8]
#7 之前提了一个merge, 修改了proxy.py文件中的变量名, 从`is_failed`改成了`was_faild`, 后来发现ProxyLog这个model里面依然使用`is_failed`字段, 是不是也应该改成`was_failed`.

    def send_proxy_log(self, data):
        """
        :param data: 格式如下
        data = {
            "user": "username",
            "asset": "name",
            "system_user": "web",
            "login_type": "ST",
            "was_failed": False,
            "date_start": timestamp,
        }
        """
        assert isinstance(data.get('date_start'), (int, float))
        data['date_start'] = timestamp_to_datetime_str(data['date_start'])
        data['was_failed'] = 1 if data.get('was_failed') else 0

        r, content = self.post('send-proxy-log', data=data, use_auth=True)
        if r.status_code != 201:
            logging.warning('Send proxy log failed: %s' % content)
            return None
        else:
            return content['id']

    def finish_proxy_log(self, data):
        """ 退出登录资产后, 需要汇报结束 时间等

        :param data: 格式如下
        data = {
            "proxy_log_id": 123123,
            "date_finished": timestamp,
        }
        """
        assert isinstance(data.get('date_finished'), (int, float))
        data['date_finished'] = timestamp_to_datetime_str(data['date_finished'])
        data['was_failed'] = 1 if data.get('was_failed') else 0
        data['is_finished'] = 1
        proxy_log_id = data.get('proxy_log_id') or 0
        r, content = self.patch('finish-proxy-log', pk=proxy_log_id, data=data)

        if r.status_code != 200:
            logging.warning('Finish proxy log failed: %s' % proxy_log_id)
            return False
        return True

**Comment by ibuler** [comment]
都修改为 is_failed吧，和数据库保持一致

**Comment by hellorocky** [comment]
OK
